spring:
  profiles:
    active: dev   # Muda automaticamente se passar SPRING_PROFILES_ACTIVE=prod no ambiente

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/clinica?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://clinica-db.ch8mgquc2p.eu-central-1.rds.amazonaws.com:3306/clinica?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    url: jdbc:mariadb://localhost:3306/clinica?useSSL=false&serverTimezone=UTC
    user: root
    password: 1234
    baseline-on-migrate: true
    # Força detectar como MySQL
    driver-class-name: org.mariadb.jdbc.Driver

---
jwt:
  secret: caizabrundavi
  expiration-ms: 3600000

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  security:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:clinica_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false   # Desativa o Flyway nos testes, pois o H2 criará o schema automaticamente
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG


