spring:
  profiles:
    active: dev   # Muda automaticamente se passar SPRING_PROFILES_ACTIVE=prod no ambiente

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/clinica?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name:  org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://clinica-db.ch8mgquc2p.eu-central-1.rds.amazonaws.com:3306/clinica?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name:  org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

---
jwt:
  secret: caizabrundavi
  expiration-ms: 3600000

server:
  port: 8080
