spring:
  profiles:
    active: dev   # ou staging, ou prod

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/clinica
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: staging
  datasource:
    url: jdbc:mysql://clinica-db.ch8mqugqcu2p.eu-central-1.rds.amazonaws.com:3306/clinica
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://clinica-db.ch8mqugqcu2p.eu-central-1.rds.amazonaws.com:3306/clinica
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
