jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mariadb:
        image: mariadb:10.11
        env:
          MARIADB_DATABASE: clinica
          MARIADB_USER: root
          MARIADB_ROOT_PASSWORD: 1234
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      
      - name: Wait for MariaDB to start
        run: |
          echo "Waiting for MariaDB..."
          for i in {1..10}; do
            nc -z localhost 3306 && echo "MariaDB is up!" && break
            echo "Waiting 5s..."
            sleep 5
          done
      
      - name: Build with Maven
        run: mvn -B clean verify
