name: CI/CD - Spring Boot on Elastic Beanstalk

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # =========================
  # 1. Build
  # =========================
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/app.jar

  # =========================
  # 2. Test
  # =========================
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test

  # =========================
  # 3. Deploy to STAGING
  # =========================
  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: target
      - name: Deploy to Elastic Beanstalk (Staging)
        uses: einaregilsson/beanstalk-deploy@v21
        with:
            application_name: clinica-backend
            environment_name: clinica-staging-env
            version_label: ${{ github.run_number }}-${{ github.sha }}
            region: eu-central-1
            deployment_package: target/app.jar
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            wait_for_deployment: true


  # =========================
  # 4. Deploy to PRODUCTION (Manual Approval)
  # =========================
  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: production
      url: http://clinica-prod-env.eba-xzv2ekxq.eu-central-1.elasticbeanstalk.com/
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: target
  
      - name: Deploy to Elastic Beanstalk (Production)
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: clinica-backend
          environment_name: clinica-prod-env
          region: eu-central-1
          version_label: ${{ github.run_number }}-${{ github.sha }}
          deployment_package: target/app.jar
          use_existing_version_if_available: true 
          wait_for_deployment: true
  
            
